name:                devops-task
version:             0.1.0.0
#synopsis:
#description:
github:              on-ramp/devops-task
license:             MIT
author:              Coinweb ltd.
maintainer:          juan@coinweb.io
copyright:           2020 Coinweb ltd.
category:            api
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bifunctors
  - containers
  - directory
  - either
  - fast-logger
  - lens
  - mtl
  - raw-strings-qq
  - servant
  - servant-server
  - sqlite-simple
  - sqlite-simple-errors
  - text
  - temporary
  - time
  - transformers
  - wai
  - wai-extra
  - warp


library:
  source-dirs: src
  exposed-modules:
    - Devops.Api
    - Devops.Config
    - Devops.Lib

default-extensions:
  - OverloadedStrings

executables:
  devops-api:
    source-dirs:
      - app
    main: Main.hs
    dependencies:
      - base
      - devops-task
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - base64-bytestring
      - bytestring
      - containers
      - hspec == 2.*
      - hspec-expectations-lifted
      - hspec-wai
      - hspec-wai-json
      - http-types
      - mtl
      - QuickCheck
      - servant
      - servant-server
