
version: 2

#-- https://circleci.com/docs/2.0/writing-yaml/ --#

globals: &globals
  docker:
    - image: fpco/stack-build-small:lts-14.5
    - image: docker:19.03-git

  environment:
    - STACK_ROOT: /home/stackage/.stack

  working_directory: /opt/CI

#-- https://circleci.com/docs/2.0/configuration-reference/ --#

jobs:
  compile-and-test:
    <<: *globals

    steps:
      - restore_cache:
          name: "Loading cached stack snapshot index"
          keys: [ stack-snapshot-index.v0 ]
          paths:
            - /home/stackage/.stack

      - run:
          name: "Updating stack package index"
          command: |
            stack --no-terminal update

      - save_cache:
          name: "Caching stack snapshot index"
          when: on_success
          key: stack-snapshot-index.v0.{{ checksum "/home/stackage/.stack/stack.sqlite3" }}
          paths:
            - /home/stackage/.stack

      - checkout

      - run:
          name: "Compiling dependencies"
          command: |
            stack -j1 --no-terminal \
                build --test --only-dependencies

      - run:
          name: "Compiling app"
          command: |
            stack -j1 --no-terminal \
                build --test --no-run-tests

      - run:
          name: "Running unit-tests"
          command: |
            stack test

      - run:
          name: "Making release binary"
          command: |
            stack install \
                  --system-ghc \
                  --local-bin-path stack-OUT

      - persist_to_workspace:
          root: .
          paths:
            - stack-OUT

  build-release-image:
    <<: *globals

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /opt/CI/stack-OUT

      - run:
          name: Building release image
          command: |
            docker build \
                  -f .circleci/app-release.dockerfile \
                  --cache-from appimg \
                  --tag devops-api:latest \
                  .

  publish-release-image:
    <<: *globals

    steps:
      - setup_remote_docker

    - run:
        name: "Show known docker images"
        command: docker images

    - run:
        name: "DockerHub login"
        command: >
          docker login -u ulidtko --password-stdin index.docker.io <<< "$DOCKERHUB_TOKEN"

    - run:
        name: "Push image"
        command: >
          docker push devops-api:latest

    - run:
        name: "Cleanup"
        command: docker logout; rm -fv ~/.docker/config.json

  docker-warmup:
    <<: *globals

    steps:
      - setup_remote_docker

      - restore_cache:
          keys:
            - docker-build-cache.v0.{{ .Branch }}
          paths:
            - /docker-cache/appimg.tar

      - run:
          name: "Load Docker build cache"
          command: |
            docker load < /docker-cache/appimg.tar || :

  docker-shutdown:
    <<: *globals

    steps:
      - run:
          name: "Save Docker build cache"
          command: |
            docker save > /docker-cache/appimg.tar

      - save_cache:
          key: docker-build-cache.v0.{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /docker-cache/appimg.tar


#-- https://circleci.com/docs/2.0/workflows/ --#

workflows:
  version: 2

  pipeline-main:
    jobs:
      - docker-warmup

      - compile-and-test

      - build-release-image:
          requires:
            - docker-warmup
            - compile-and-test

      - publish-release-image:
          requires:
            - build-release-image

      - docker-shutdown:
          requires:
            - docker-warmup
            - build-release-image

    #filters:
    #  branches:
    #    - master
    #    - develop
