
version: 2

#-- https://circleci.com/docs/2.0/writing-yaml/ --#

globals: &globals
  working_directory: /opt/CI

#-- https://circleci.com/docs/2.0/configuration-reference/ --#

jobs:
  compile-and-test:
    <<: *globals

    docker:
      - image: fpco/stack-build-small:lts-14.5

    environment:
      - STACK_ROOT: /home/stackage/.stack

    steps:
      - run:
          name: "Updating stack package index"
          command: |
            stack --no-terminal update

      - checkout

      - restore_cache:
          name: "Loading warm built deps"
          keys:
            - v1-built-deps-{{ checksum "stack.yaml.lock" }}
            - v1-built-deps-
          paths:
            - .stack-work/install

      - run:
          name: "Compiling dependencies"
          command: |
            stack -j1 --no-terminal \
                build --test --only-dependencies

      - save_cache:
          name: "Caching built deps"
          key: v1-built-deps-{{ checksum "stack.yaml.lock" }}
          paths:
            - .stack-work/install

      - run:
          name: "Compiling app"
          command: |
            stack -j1 --no-terminal \
                build --test --no-run-tests

      - run:
          name: "Running unit-tests"
          command: |
            stack test

      - run:
          name: "Making release binary"
          command: |
            stack install \
                  --system-ghc \
                  --local-bin-path stack-OUT

      - persist_to_workspace:
          root: .
          paths:
            - stack-OUT


  build-release-image:
    docker:
      #-- Ceci n'est pas une DinD
      - image: docker:19.03-git

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /opt/CI/stack-OUT

      - run:
          name: "Building release image"
          command: |
            docker build \
                  -f .circleci/app-release.dockerfile \
                  --cache-from appimg \
                  --tag devops-api:latest \
                  .


  publish-release-image:
    docker:
      - image: docker:19.03-git

    steps:
      - setup_remote_docker

      - run:
          name: "Show known docker images"
          command: docker images

      - run:
          name: "DockerHub login"
          command: >
            docker login -u ulidtko --password-stdin index.docker.io <<< "$DOCKERHUB_TOKEN"

      - run:
          name: "Push image"
          command: >
            docker push devops-api:latest

      - run:
          name: "Cleanup"
          command: >
            docker logout; rm -fv ~/.docker/config.json


#-- https://circleci.com/docs/2.0/workflows/ --#

workflows:
  version: 2

  pipeline-main:
    jobs:
      - compile-and-test

      - build-release-image:
          requires:
            - compile-and-test

      - publish-release-image:
          requires:
            - build-release-image

    #filters:
    #  branches:
    #    - master
    #    - develop
